spring:
  application:
    name: productsCrud

  datasource:
    url: jdbc:postgresql:///app_db
    username: app_user
    password: secret999

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
token:
  expires-in: 3600
  secret: FVPr6Q/fVlHGZkElZubC0Zaxv657dPUfDQ4o9DADjSin7+uST1d2A5klMWrMK8fmSl3doyf2wn5zj56VC+qqCg==
